### ISSUE TITLE
Fix footer section text color is not stable

### ISSUE THREAD

**Issue by nanophate** [yasslab/coderdojo.jp#10]
フッターのセクションにテキストを追加した時に色が反映されないことがある。
![](https://uploads.intercomcdn.com/i/o/6803211/24553e1afb11305845217914/Screen%2520Shot%25202016-05-30%2520at%25204.47.29%2520PM.png)

**Comment by yasulab** [comment]
これは直ってるので閉じちゃいますね ;)
