### ISSUE TITLE
Add book page

### ISSUE THREAD

**Issue by nanophate** [yasslab/coderdojo.jp#16]
# Goal

Use an existing blog page and overviewBlog page to generate site like this 👇 

<img width="872" alt="screen shot 2016-10-24 at 18 15 24" src="https://cloud.githubusercontent.com/assets/6015450/19640031/de688a28-9a15-11e6-872a-4c1cb0d47d4d.png">

## TODO

- [x] Add Abstract
- [x] Add cover Image
- [x] Organize Design

**Comment by yasulab** [comment]
これは粒度が大きい Issue になっているのと、細かい Issue に十分に分けられていると思うのでこれも閉じちゃいます ><
