### ISSUE TITLE
素材のダウンロード機能を追加する

### ISSUE THREAD

**Issue by tomoko523** [yasslab/coderdojo.jp#40]
http://coderdojo.jp/sotechsha-gazou

**Comment by tomoko523** [comment]
これで実装できそう。使い方について調査する。

> Returns the file extension (e.g. zip, pdf) of this link's (internal or external) target. Returns an empty string if the file extension is can not be determined.



```
# File 'lib/scrivito/link.rb', line 118
def file_extension
  if internal?
    obj ? obj.file_extension : ""
  else
    path = URI.parse(url).path rescue nil
    path.blank? ? "" : File.extname(path)[1..-1] || ""
  end
end
```


http://www.rubydoc.info/gems/scrivito_sdk/0.50.1/Scrivito%2FLink%3Afile_extension

**Comment by tomoko523** [comment]
できた。
aリンク先にダウンロードしたいzipを紐づけるとできます。


<img width="1440" alt="2016-12-15 12 07 38" src="https://cloud.githubusercontent.com/assets/11689944/21210552/62b8c212-c2bf-11e6-86a1-708a75f70dc0.png">

<img width="489" alt="2016-12-15 12 08 02" src="https://cloud.githubusercontent.com/assets/11689944/21210538/4267e24a-c2bf-11e6-96fe-c55f14cd230d.png">

<img width="593" alt="2016-12-15 12 04 54" src="https://cloud.githubusercontent.com/assets/11689944/21210490/d912ebc8-c2be-11e6-8bfb-f6cff59c1977.png">

**Comment by tomoko523** [comment]
@yasulab 
↑この場合ダウンロード素材がscrivito側のサーバに保存されますが、
この点については問題ないですが？

**Comment by yasulab** [comment]
@tomoko523 ダウンロード素材は CC BY-NC 4.0 Internaional で公開することになっているので大丈夫です! 👌 

また、Scrivito 側にあるとホスティング的な側面から見ても安心できそう 😊 (負荷が分散されるので)

**Comment by tomoko523** [comment]
@yasulab ありがとうございます！
この対応は実装を直すことはないので、このままCloseしてしまいますね。

(/sotechsha-gazou）に実装例を載せています。

**Comment by yasulab** [comment]
> この対応は実装を直すことはないので、このままCloseしてしまいますね。

了解です! 👌 お疲れ様でした〜♨️
