### ISSUE TITLE
CoderDojo Japan 公式ブック デザイン修正箇所まとめ

### ISSUE THREAD

**Issue by yasulab** [yasslab/coderdojo.jp#62]
__〆切: 今日中に終わらせる__ ✅ 

CoderDojo Japan 公式ブック
http://coderdojo.jp/sotechsha

## 対応する

- [x] 書籍画像の下に文言を追加: 
   -  『このコンテンツでは書籍内に利用する素材と発展課題の模範解答を掲載しています。』
- [x] SNSボタンはトップページ (/sotechsha) にのみ描画
- [x] footer に関連サイトを設置:
   - coderdojo.jp へのリンク
   - Amazonへのリンク
   - 書籍の正誤表ページへのリンク
- [x] footer にcopyrightを設置
- [x] footerの直前にサイトマップを作成する
   - /sotechsha 
   - /sotechsha/* のすべてのリンクにワンタップで飛べる
- [x] 文言やabstractのチェック
- [x] iOS/Androidでチェック
- [x] タイトルのリンクを消す
- [x] タイトルを強調する (bold?)
- [x] フォントサイズの大きさがバラバラなので、１〜２種類にまとめる
    - もしくは、フォントカラーにもう１色追加する (表紙の色に合わせて、緑 or 黄色 or オレンジとか)

## 余裕があれば

- [ ] Rename: so_tech_sha -> sotechsha https://github.com/yasslab/coderdojo.jp/issues/59
- [ ] public/ 以下にある静的ファイルを app/assets 以下に移す #35

**Comment by tomoko523** [comment]
@yasulab footerはトップページに追加ですか？すべてのページでしょうか。

**Comment by yasulab** [comment]
@tomoko523 partial化して、一旦はすべてのページに追加してみましょう。デザイン的に微妙だったらpartialごと外せばよいだけなので ;)

**Comment by tomoko523** [comment]
@yasulab わかりました！

**Comment by yasulab** [comment]
`余裕があれば`の項目はそれぞれ別の Issue として切り出したので、こちらの Issue としてはいったんこれで完了としますね! 😸  ✅ ✨ 

cc/ @tomoko523
